### ISSUE TITLE
loading CDA crashes python session: Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by afrigeri** [AlliedToasters/PyCDA#1]
using iPython 3.7.3 (default, Oct  7 2019, 12:56:13)

> 
>In [1]: from pycda import CDA, load_imageIn 
>In [2]: cda = CDA()                                                                                                                                   
>Illegal instruction (core dumped)
>

**Comment by AlliedToasters** [comment]
Python 3.7 is not supported, unfortunately. Please use python 3.6.

**Comment by AlliedToasters** [comment]
https://github.com/AlliedToasters/PyCDA/blob/master/readme.md
